export { default as Layout } from './Layout'
export { default as VersionOne } from './VersionOne'
export { default as VersionTwo } from './VersionTwo'
export { default as VersionThree } from './VersionThree'
export { default as LayoutForm } from './LayoutForm'
export { default as Form } from './Form'
export { default as Thanks } from './Thanks'